#!/bin/bash

homedir=/usr/lib/totp/

mkdir -p $homedir
cp providers.json $homedir
cp package.json $homedir
cp *.js $homedir

cd $homedir
npm install

echo "Consider running pm2 start ${homedir}server.js to set up or pm2 restart"