#!/bin/bash

homedir=/usr/lib/totp/

mkdir -p $homedir
cp providers.json $homedir
cp package.json $homedir
cp *.js $homedir

cd $homedir
npm install

echo "Consider running pm2 start $homedir/serve.js"